# ==========================================
# 1. CẤU HÌNH ĐẦU RA (BẮN VÀO RABBITMQ)
# ==========================================
debezium.sink.type=rabbitmq
debezium.sink.rabbitmq.connection.host=host.docker.internal
debezium.sink.rabbitmq.connection.port=5673
debezium.sink.rabbitmq.connection.username=admin
debezium.sink.rabbitmq.connection.password=123456
debezium.sink.rabbitmq.routingKey=debezium.oracle.events

# ==========================================
# 2. CẤU HÌNH ĐẦU VÀO (ĐỌC TỪ ORACLE LOGMINER)
# ==========================================
debezium.source.connector.class=io.debezium.connector.oracle.OracleConnector
debezium.source.database.hostname=host.docker.internal
debezium.source.database.port=1521
debezium.source.database.user=c##dbzuser
debezium.source.database.password=123456
debezium.source.database.dbname=XE
debezium.source.database.pdb.name=TongBo
debezium.source.topic.prefix=oracle_sync

# Chỉ theo dõi một số bảng cụ thể để đỡ lag
debezium.source.table.include.list=.*\.(KHACHHANG|HOPDONG|HOADON)

# ==========================================
# 3. BỘ NHỚ CỦA DEBEZIUM (LƯU VÀO Ổ CỨNG DOCKER)
# ==========================================
# Lưu tọa độ đọc log (Offset)
debezium.source.offset.storage=org.apache.kafka.connect.storage.FileOffsetBackingStore
debezium.source.offset.storage.file.filename=/debezium/data/offsets.dat
debezium.source.offset.flush.interval.ms=60000

# Lưu lịch sử cấu trúc bảng (Schema History)
debezium.source.schema.history.internal=io.debezium.storage.file.history.FileSchemaHistory
debezium.source.schema.history.internal.file.filename=/debezium/data/schema_history.dat